name: kibot-workflow

on: [push, pull_request]

jobs:
  generate-schematic:
    runs-on: ubuntu-latest
    container: kicad/kicad:8.0.0
    steps:
    - uses: actions/checkout@v4
    - name: Generate schematic
      run: sudo kicad-cli sch export pdf -o Untitled.pdf Untitled.kicad_sch
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: Untitled.pdf